# -*- coding: utf-8 -*-
"""Week_1(Portfolio).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uXluN--YU9jXjpVNQR-XilWetal8k23
"""

# for loop example
for z in range(10,100,2):
  print(z,end=" ")

#list Example
a=[2,4,6,8,9,12,15]
print(f"total members in list is {len(a)}")
print(a[2])
a[5]=14
print(a[5])
print(min(a),max(a))
a.append(2234)
print(f"total members in list is {len(a)}")

print(a[7])

#Local and global variable in python
gvariable=10
def listsum(numList):


  global gvariable
  gvariable =20
  print(f"value of the gvariable is {gvariable}")
  theSum=0 # this a variable to hold sum
  for i in numList:  # for loop to access all the list members
    theSum=theSum+i  # to sum all the members
  count=len(numList)
  print(f"count of the  list is {count}")
  return theSum,count # return the sum

print(f"value of g variable before callin the function {gvariable}")
mylist=[3,14,5,6,17,8,19,0]
Sm,cnt=listsum(mylist)
print(f"sum of the list is {Sm}")
print(f"count of the list is {cnt}")
print(f"value of g variable after callin the function {gvariable}")

a=[]
even=[]
odd=[]
for i in range(1,101,1):
  if (i%2==0):
    even.append(i)
  else:
    odd.append(i)
  a.append(i)
print(f"total members of the list is {len(a)}")
print(f"total members of the even list is {len(even)}")
print(f"total members of the odd list is {len(odd)}")

#use of pandas
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
print(df.shape)
df.head()

#iris.data contains only the feature values (like sepal length, petal width, etc.) for each sample.
#iris.target is a separate array that holds the numeric species code (0, 1, or 2) for each sample.
iris = load_iris()
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
df.head()

import matplotlib.pyplot as plt
plt.hist(df['sepal length (cm)'], bins=20, color='skyblue', edgecolor='black')
plt.title('Sepal Length Distribution')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Frequency')
plt.show()

import seaborn as sns
sns.boxplot(x='species', y='petal width (cm)', data=df)
plt.title('Petal Width by Species')
plt.show()

sns.scatterplot(x='petal length (cm)', y='petal width (cm)', hue='species', data=df)
plt.title('Petal Length vs Petal Width')
plt.show()

corr = df.iloc[:, :-1].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.show()

grouped_df = df.groupby('species').mean()
grouped_df

"""In this first week lab, we have worked on python basics that includes for-loops, lists, global and local variables, and simple data processing. So, we have created list, then we also accessed the elements of the list, updated it as well along with counting how many items it contains. We also did loops that seperate the even and odd numbers. After that, we worked on using iris dataset with pandas to load data into the dataframes. Then we also checked its shape, added species coloumn and viewd the first few rows. This exercies made me learn more about pandas, and its functions like how it organize the data. In this lab we also used matplotlib and seaborn to create histogramsboxplots, scatterplots and heatmaps. Then also learned about grouping works that calculate the average values of the species."""